# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/naruto900814"
  # weibo: ""
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  mail: "mailto:lsy814@gmail.com"
  #facebook: "#"
  # google: "mailto:lsy814@gmail.com"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "https://avatars0.githubusercontent.com/u/5361460?v=3&u=fba7111af267cba8fa0eab29a88caf7b0fa34b4a&s=140"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 目前就职于狗场的一个移动方向小程序猴，热爱移动的各种知识，html5、ios、android就是任性的爱。 